enum PermissionId {
	USER_CREATE_ANY = "USER:CREATE:ANY",
	USER_DELETE_ANY = "USER:DELETE:ANY",
	USER_UPDATE_ANY = "USER:UPDATE:ANY",
	USER_UPDATE_OWN = "USER:UPDATE:OWN",
}

export {
	PermissionId,
};
